# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Authentication CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test-clinic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies (Auth Microservice)
        run: npm ci
        working-directory: authentication

      - name: Run ESLint (Auth Microservice)
        run: npm run lint
        working-directory: authentication

      - name: Run Tests (Auth Microservice)
        run: npm run test
        working-directory: authentication
env:
  MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}

