# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Clinic CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint-and-test-clinic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker
        run: docker-compose up -d

      - name: Wait for Kafka to be ready
        run: npx wait-on tcp:127.0.0.1:${{ secrets.KAFKA_PORT }} && echo "Kafka is ready!"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies (Clinic Microservice)
        run: npm ci
        working-directory: clinic

      - name: Run ESLint (Clinic Microservice)
        run: npm run lint
        working-directory: clinic

      - name: Run Tests (Clinic Microservice)
        run: npm run test
        working-directory: clinic

env:
  MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
  ZOOKEEPER_PORT: ${{ secrets.ZOOKEEPER_PORT }}
  KAFKA_PORT: ${{ secrets.KAFKA_PORT }}
  ZOOKEEPER_HOST_NAME: ${{ secrets.ZOOKEEPER_HOST_NAME}}
